apiVersion: v1
kind: Secret
metadata:
  name: my-secret
type: Opaque
data:
  username: eW91ci11c2VybmFtZQ==  # base64-encoded 'your-username'
  password: eW91ci1wYXNzd29yZA==  # base64-encoded 'your-password'
