name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4  # Atualize para a versão mais recente

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3  # Atualize para a versão mais recente
        with:
          terraform_version: 1.5.0

      - name: Terraform Init
        run: terraform init

      - name: Terraform Plan
        run: terraform plan

      - name: Terraform Apply
        run: terraform apply -auto-approve

      - name: Set up kubectl
        uses: azure/setup-kubectl@v1
        with:
          version: '1.25.0'

      - name: Configure kubeconfig
        run: |
          echo "${{ secrets.KUBE_CONFIG_DATA }}" > $HOME/.kube/config

      - name: Deploy to Kubernetes
        run: |
          kubectl apply -f deployment.yaml
          kubectl apply -f service.yaml
          kubectl apply -f ingress.yaml
          kubectl apply -f hpa.yaml
          kubectl apply -f certificate.yaml
          kubectl apply -f cluster-issuer.yaml
